CREATE TABLE IF NOT EXISTS PACIENTES (ID INT AUTO_INCREMENT PRIMARY KEY, NOMBRE VARCHAR(100), APELLIDO VARCHAR(100), DOMICILIO VARCHAR(255), DNI INT, FECHA_DE_ALTA DATE);
CREATE TABLE IF NOT EXISTS ODONTOLOGOS (ID INT AUTO_INCREMENT PRIMARY KEY, NOMBRE VARCHAR(100), APELLIDO VARCHAR(100), MATRICULA INT);
CREATE TABLE IF NOT EXISTS DOMICILIOS (ID INT AUTO_INCREMENT PRIMARY KEY, CALLE VARCHAR(100), LOCALIDAD VARCHAR(100), PROVINCIA VARCHAR(100), NUMERO INT);
CREATE TABLE IF NOT EXISTS USUARIOS (ID INT AUTO_INCREMENT PRIMARY KEY, USUARIO VARCHAR(100), PASSWORD VARCHAR(100), ROL_FK INT);
CREATE TABLE IF NOT EXISTS TURNOS (ID INT AUTO_INCREMENT PRIMARY KEY, PACIENTE_FK INT, ODONTOLOGO_FK INT, FECHA DATE, HORA TIME);